spring:
  jwt:
    secret: ZGF5b25lLXNwcmluZy1ib290LWRpdmlkZW5kLXByb2plY3QtdHV0b3JpYWwtand0LXNlY3JldC1rZXkKfdieJFKElfjdows3mfn

oauth:
  kakao:
    client-id: e207c7b2bb2c175cfa7b36713d5fd29a
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
  google:
    client-id: 786993775110-2ovjaiidekvcocqolmpij3rn2nnobjj5.apps.googleusercontent.com
    secret: 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
    url:
      redirect: http://localhost:8080/login/oauth2/code/google
      auth: https://oauth2.googleapis.com/token
      api: https://www.googleapis.com

